# Site settings
title: Tanuj Vishnoi [SDET]
name: Tanuj Kumar Vishnoi

# Build settings
markdown: kramdown

#User specific content

#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://automateddeveloper.blogspot.com/
 - title: GitLab
   url: https://github.com/tanuj-vishnoi
 - title: StackOverflow
   url: https://stackoverflow.com/users/4378647/tanuj-vishnoi
 - title: Blog
   url: https://tanujvishnoi.wixsite.com/website
 - title: LinkedIn
   url: https://www.linkedin.com/in/tanuj-vishnoi-4976568a/

#Any buzzword skills you want to include
skills:
 - TestNG
 - Cucumber
 - Junit
 - NUnit
 - Mocha
 - Cypress
 - Chai
 - AssertJ
 - RestAssured
 - Node/Javascript
 - Java
 - C#
 - Groovy
 - Git
 - Jenkins
 - TeamCity
 - GitLabPiplines
 - HTML
 - Vanila Javascript
 - Product Management
 - Maven
 - NPM
 - Allure
 - Extent Report
 - Test Framework 
 - keyword Drivern
 - Data Driven and Hybrid
 - API Automation [Coded and Codeless]
 - UI Automation [Coded and Codeless]
 - DeskTop Automation [Sikuli/AutoIt/Winnium]
 - Spring Boot/Express [Begineer for api development]
 - Mocking [Fiddler/Puppeter]
 - TMS Integration [TestRail/ JIRA / VSTS]
 - Server Side Automation
 - Mobile Testing
 - Test Plan
 - API Testing[Rest and SOAP]
 - DataBase Testing
 - AWS
#Work experience is required
roles:
 - title: Lead Engineer Test Automation
   start: 2018
   end: Ongoing
   employer: QAInfotech Private Limited
   description: As a Lead Engineer, my resposibilty is to ensure smooth projects delivarable, provide solution for automation blocker, review code , create test plan, ensure test code quality, draft test automation strategies , demo on new testing tools to client/internal team, create demo for new prospective clients, test estimation
 - title: Senior Software Engineer - Test Automation
   start: 2017
   end: 2018
   employer: QAInfotech Private Limited
   description: As a senior resource I took care of client communication in scrum meetings, create test cases, create test plan, test case automation, handling team member and distributing work amongst them
 - title: Test Automation Engineer II
   start: 2016
   end: 2017
   employer: QAInfotech Private Limited
   description: Draft test cases as per the user stories and automate them as per the sprint planning. Log issue and update test results to test management server as per the latest result
 - title: Test Automation Engineer
   start: 2014
   end: 2016
   employer: QAInfotech Private Limited
   description: Perform all the smoke, sanity and daily execution of regression check on the test servers. Automate test cases assigned by the the senior resources

#Education is required
education:
 - level: Master of Computer Application
   date: 2014
   subject: Computer Applications
   college: Birla Institue of Applied Sciences Bhimtal, Nainital, Uttarakhand
   description: I did bachelor in mathematics and chemistry , after that I did master in compture applications from BIAS bhimtal


intro: |
  I am an engineer with 6 years experience working in Software Industry and now days I am wroking in Quality Assurance divison as Lead Software Enginner in Test Automation. 
  I have an expertise in test framework development for web application, server side interface and mobile application. 
  Working in the Agile methodolgies to ensure the Quality of the products as per the specifications

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>UI Automation</strong>:  I have been working with UI automation tools/frameworks since the starting of my carrer and able to provide customize UI automation solution as per the application requirement. 
   <br/>
   <br/>
   <strong>API Automation</strong>: Rich experience in server side automation using the pojo based approach with coded solution. Although I have worked with codeless tools as well like SOAPUI/Postman
   <br/>
   <br/>
   <strong>Desktop Automation</strong>: Solved many of the desktop UI interaction problem using sikuli and autoIt tools and integrated them with the main stream projects
   <br/>
   <br/>
   <strong>Web Development</strong>: Never worked on a real time webdevelopment projects, but I have a self learning exp with node express and spring boot projects. Worked with bootstrap as well to creating web pages for internal purposes. Also created different api clients for the purpose of TMS integration
   <br/>
   <br/>
   <strong>CI Integration</strong>: Hands on expereince with CI tools like Jenkins to deploy and schedule jobs. Also worked with pipelines as well
   <br/>
   <br/>
   <strong>Device Automation</strong>: Handled/Automated android/ios based Ui application using the Appium like tool
